# Generated by Django 3.2.7 on 2022-02-13 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='state',
            field=models.CharField(choices=[('ST', 'sent'), ('SE', 'send error')], default='sent', max_length=20, verbose_name='статус сообщения'),
        ),
    ]
