# Generated by Django 3.2.7 on 2022-02-19 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_message_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sending_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='время отправки сообщения'),
        ),
        migrations.AlterField(
            model_name='message',
            name='state',
            field=models.CharField(choices=[('1', 'ready'), ('2', 'in progress'), ('3', 'in progress'), ('4', 'sent'), ('5', 'send error')], default='1', max_length=20, verbose_name='статус сообщения'),
        ),
    ]
